GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/618c561e99f909c37f6fa47b

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "Igor Entaltsev",
    "subscribedToChannel": "Personal Channel"
}

### 

DELETE http://localhost:3000/subscribers/618c561e99f909c37f6fa47b

###

PATCH http://localhost:3000/subscribers/618c5c005db23c0875b64123
Content-Type: application/json

{
    "name": "Jenica Entaltseva"
}
