GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/618c561e99f909c37f6fa47b

###

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
    "name": "Igor Entaltsev",
    "subscribedToChannel": "Personal Channel"
}